### ISSUE TITLE
 ids_to_keys() gives incorrect output

### ISSUE THREAD

**Issue by zhizhang77** [Choco31415/Attention_Network_With_Keras#2]
IMO you should sort the list before indexing.

    return [sorted(list(vocab.keys()))[id] for id in sentence]

BTW, very helpful tutorial. Thanks for sharing~

**Comment by Choco31415** [comment]
Good find, that code is janky - dict's don't give a guaranteed order for keys.

However, sort() won't fix that line as the alphabetic ordering might not match id ordering. In the example, keys just happen to be sorted both alphabetically and by id.

The best option is to build a reverse dictionary (or list, as it just happens to work).

 I'll get this in soon, it might take me a day or two to swing around. :/

**Comment by Choco31415** [comment]
Fix verified locally and pushed.
